# Generated by Django 4.0.6 on 2022-08-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('itemsJson', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
