# Generated by Django 4.0.6 on 2022-08-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='itemsJson',
            field=models.CharField(max_length=5000),
        ),
    ]
