# Generated by Django 4.0.6 on 2022-08-13 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_itemsjson_orders_items_json_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
