# Generated by Django 4.0.6 on 2022-08-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=700)),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
